[package]
name = "character-prediction"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = "0.7.0"  # Older version that doesn't require edition2024
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.100"
